version: '3.7'

services:
  db:
    image: postgres
    container_name: rlsp_postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: canadiancities
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - "5433:5432"
    volumes:
      - ./rlsp_postgres_data:/var/lib/postgres/data
    mem_limit: 512M

  prometheus:
    image: prom/prometheus:latest
    container_name: rlsp_canadians_cities_prometheus
    volumes:
      - "./main/resources/prometheus.yml:/etc/prometheus/prometheus.yml"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    mem_limit: 128M

  grafana:
    image: grafana/grafana:latest
    container_name: rlsp_canadians_cities_grafanaa
    ports:
      - "3000:3000"
    mem_limit: 128M


volumes:
  rlsp_postgres_data: